### ISSUE TITLE
Make sure plot does not slow down ipopt

### ISSUE THREAD

**Issue by pariterre** [pyomeca/BiorbdOptim#153]

**Comment by pariterre** [comment]
Make sure the communication between the processors are using UDP and not TCP, which could slow things down otherwise

**Comment by EveCharbie** [comment]
Working on it :)

**Comment by EveCharbie** [comment]
It does slow down IPOPT. I tested with maximize_predicted_height_CoM, results are as follow:

1) Test for t = 5, ns = 200
With plots : 19.38321542739868 s
Without plots : 18.32109808921814 s
2) Test for t = 50, ns = 200
With plots : 342.2361035346985 s
Without plots : 307.77546977996826 s

I think the problem is at recv : "[recv] Bloque jusqu'à ce que quelque chose soit reçu." https://docs.python.org/fr/3/library/multiprocessing.html

Possible avenues for solution:
1) Treat arg[0] as a socket data flow with recvfrom (class socket) which is the UDP version of recv. https://pythontic.com/socketserver/threadingudpserver/introduction
2) Use multiprocessing.sharedctypes to access shared memory (bypass recv). https://docs.python.org/fr/3/library/multiprocessing.html

**Comment by EveCharbie** [comment]
I implemented the shared memory option. It still slows down Ipopt :(
Results for 30 trials of maximized_predicted_height_CoM:
with plots : 20.52554191748301 +- 1.12808514596442
without plots : 17.647579884529115 +- 0.39544275397521056

**Comment by pariterre** [comment]
So it is the same order of magnitude? Could you redo the one which was taking 5 minutes? If it gives the same thing, then I think we can leave it as is (since we will never do faster than shared memory)

**Comment by EveCharbie** [comment]
maximized_predicted_height_CoM, ns = 200, t = 50: 
with graphs results : 323.4463245312373 +- 18.840376615154913
without graphs results : 282.86038216749824 +- 5.873278186064388

**Comment by pariterre** [comment]
It seems that shared memory or send/recv are equivalent. Since the one already implemented works, I think we will keep it. Thanks for answering this Issue!
GJ :)

**Comment by mickaelbegon** [comment]
Is it possible to add this information somewhere that realtime plots may affect speed of about 15%?
